// frontend/nuxt3/app/components/PermissionGuard.vue
<template>
  <slot v-if="allowed" />
  <slot v-else name="fallback">
    <div class="text-center py-12 text-gray-500">
      You don't have permission to access this section.
    </div>
  </slot>
</template>

<script setup lang="ts">
import type { Permission } from '~/types';

const props = defineProps<{
  permission?: Permission;
  permissions?: Permission[];
  requireAll?: boolean;
}>();

const { hasPermission, hasAnyPermission, hasAllPermissions } = usePermissions();

const allowed = computed(() => {
  if (props.permission) {
    return hasPermission(props.permission);
  }
  if (props.permissions) {
    return props.requireAll
      ? hasAllPermissions(props.permissions)
      : hasAnyPermission(props.permissions);
  }
  return true;
});
</script>

// frontend/react/src/shared/components/PermissionGuard.tsx
import type { ReactNode } from 'react';
import { useAuth } from '../../features/auth/hooks/useAuth';
import type { Permission } from '../types';
import { hasPermission, hasAnyPermission, hasAllPermissions } from '../utils/permissions';

interface PermissionGuardProps {
  permission?: Permission;
  permissions?: Permission[];
  requireAll?: boolean;
  fallback?: ReactNode;
  children: ReactNode;
}

export function PermissionGuard({
  permission,
  permissions,
  requireAll = false,
  fallback = null,
  children,
}: PermissionGuardProps) {
  const { user } = useAuth();

  if (permission) {
    return hasPermission(user, permission) ? <>{children}</> : <>{fallback}</>;
  }

  if (permissions) {
    if (requireAll) {
      return hasAllPermissions(user, permissions) ? <>{children}</> : <>{fallback}</>;
    }
    return hasAnyPermission(user, permissions) ? <>{children}</> : <>{fallback}</>;
  }

  return <>{children}</>;
}
