// frontend/nextjs/src/components/articles/ArticleForm.tsx
"use client";

import { useState, type FormEvent } from "react";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { TextArea } from "@/components/ui/TextArea";
import type {
  CreateArticleDTO,
  Article,
  Category,
  Tag,
} from "@/types";

interface ArticleFormProps {
  article?: Article;
  categories: Category[];
  tags: Tag[];
  onSubmit: (data: CreateArticleDTO) => void;
  isLoading: boolean;
  submitLabel: string;
}

export function ArticleForm({
  article,
  categories,
  tags,
  onSubmit,
  isLoading,
  submitLabel,
}: ArticleFormProps) {
  const [title, setTitle] = useState(article?.title ?? "");
  const [content, setContent] = useState(article?.content ?? "");
  const [excerpt, setExcerpt] = useState(article?.excerpt ?? "");
  const [selectedCategories, setSelectedCategories] = useState<string[]>(
    article?.categories.map((c) => c.id) ?? [],
  );
  const [selectedTags, setSelectedTags] = useState<string[]>(
    article?.tags.map((t) => t.id) ?? [],
  );

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    onSubmit({
      title,
      content,
      excerpt,
      categoryIds: selectedCategories,
      tagIds: selectedTags,
      coAuthorIds: [],
    });
  };

  const toggleCategory = (id: string) => {
    setSelectedCategories((prev) =>
      prev.includes(id) ? prev.filter((c) => c !== id) : [...prev, id],
    );
  };

  const toggleTag = (id: string) => {
    setSelectedTags((prev) =>
      prev.includes(id) ? prev.filter((t) => t !== id) : [...prev, id],
    );
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <Input
        label="Title"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        required
        placeholder="Article title"
      />

      <TextArea
        label="Excerpt"
        value={excerpt}
        onChange={(e) => setExcerpt(e.target.value)}
        placeholder="Brief summary of the article"
        rows={3}
      />

      <TextArea
        label="Content"
        value={content}
        onChange={(e) => setContent(e.target.value)}
        required
        placeholder="Write your article content..."
        rows={12}
      />

      {categories.length > 0 && (
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Categories
          </label>
          <div className="flex flex-wrap gap-2">
            {categories.map((category) => (
              <button
                key={category.id}
                type="button"
                onClick={() => toggleCategory(category.id)}
                className={`rounded-full px-3 py-1 text-sm font-medium transition-colors ${
                  selectedCategories.includes(category.id)
                    ? "bg-blue-100 text-blue-800"
                    : "bg-gray-100 text-gray-700 hover:bg-gray-200"
                }`}
              >
                {category.name}
              </button>
            ))}
          </div>
        </div>
      )}

      {tags.length > 0 && (
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Tags
          </label>
          <div className="flex flex-wrap gap-2">
            {tags.map((tag) => (
              <button
                key={tag.id}
                type="button"
                onClick={() => toggleTag(tag.id)}
                className={`rounded-full px-3 py-1 text-sm font-medium transition-colors ${
                  selectedTags.includes(tag.id)
                    ? "bg-green-100 text-green-800"
                    : "bg-gray-100 text-gray-700 hover:bg-gray-200"
                }`}
              >
                {tag.name}
              </button>
            ))}
          </div>
        </div>
      )}

      <div className="flex justify-end">
        <Button type="submit" isLoading={isLoading}>
          {submitLabel}
        </Button>
      </div>
    </form>
  );
}

// frontend/nuxt3/app/components/ArticleForm.vue
<template>
  <form class="bg-white rounded-lg shadow-sm p-6 space-y-6" @submit.prevent="handleSubmit">
    <div v-if="error" class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
      {{ getErrorMessage(error) }}
    </div>

    <!-- Title -->
    <div>
      <label for="title" class="block text-sm font-medium text-gray-700 mb-1">Title *</label>
      <input
        id="title"
        v-model="form.title"
        type="text"
        required
        class="w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
        placeholder="Article title"
      />
    </div>

    <!-- Excerpt -->
    <div>
      <label for="excerpt" class="block text-sm font-medium text-gray-700 mb-1">Excerpt</label>
      <textarea
        id="excerpt"
        v-model="form.excerpt"
        rows="2"
        class="w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
        placeholder="Brief description..."
      />
    </div>

    <!-- Content -->
    <div>
      <label for="content" class="block text-sm font-medium text-gray-700 mb-1">Content *</label>
      <textarea
        id="content"
        v-model="form.content"
        rows="15"
        required
        class="w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500 font-mono"
        placeholder="Write your article content..."
      />
    </div>

    <!-- Status -->
    <div>
      <label for="status" class="block text-sm font-medium text-gray-700 mb-1">Status</label>
      <select
        id="status"
        v-model="form.status"
        class="border border-gray-300 rounded px-3 py-2"
      >
        <option value="draft">Draft</option>
        <option v-if="hasPermission('article.publish')" value="in_review">In Review</option>
        <option v-if="hasPermission('article.publish')" value="published">Published</option>
        <option v-if="hasPermission('article.archive')" value="archived">Archived</option>
      </select>
    </div>

    <!-- Tags -->
    <div>
      <label class="block text-sm font-medium text-gray-700 mb-1">Tags</label>
      <div v-if="tagsLoading" class="text-sm text-gray-400">Loading tags...</div>
      <div v-else class="flex flex-wrap gap-2">
        <label
          v-for="tag in availableTags"
          :key="tag.id"
          class="flex items-center gap-1 text-sm bg-gray-50 px-2 py-1 rounded cursor-pointer hover:bg-gray-100"
        >
          <input
            v-model="form.tagIds"
            type="checkbox"
            :value="tag.id"
          />
          {{ tag.name }}
        </label>
      </div>
    </div>

    <!-- Categories -->
    <div>
      <label class="block text-sm font-medium text-gray-700 mb-1">Categories</label>
      <div v-if="categoriesLoading" class="text-sm text-gray-400">Loading categories...</div>
      <div v-else class="flex flex-wrap gap-2">
        <label
          v-for="category in availableCategories"
          :key="category.id"
          class="flex items-center gap-1 text-sm bg-gray-50 px-2 py-1 rounded cursor-pointer hover:bg-gray-100"
        >
          <input
            v-model="form.categoryIds"
            type="checkbox"
            :value="category.id"
          />
          {{ category.name }}
        </label>
      </div>
    </div>

    <!-- Submit -->
    <div class="flex justify-end gap-3">
      <NuxtLink
        to="/admin/articles"
        class="px-4 py-2 border border-gray-300 rounded text-gray-700 hover:bg-gray-50"
      >
        Cancel
      </NuxtLink>
      <button
        type="submit"
        :disabled="isSubmitting"
        class="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 disabled:opacity-50"
      >
        {{ isSubmitting ? 'Saving...' : (initialData ? 'Update' : 'Create') }}
      </button>
    </div>
  </form>
</template>

<script setup lang="ts">
import type { Article, CreateArticlePayload, UpdateArticlePayload } from '~/types';

const props = defineProps<{
  initialData?: Article;
  isSubmitting: boolean;
  error: Error | null;
}>();

const emit = defineEmits<{
  submit: [payload: CreateArticlePayload | UpdateArticlePayload];
}>();

const { hasPermission } = usePermissions();
const { data: availableTags, isLoading: tagsLoading } = useTags();
const { data: availableCategories, isLoading: categoriesLoading } = useCategories();

const form = reactive({
  title: props.initialData?.title || '',
  content: props.initialData?.content || '',
  excerpt: props.initialData?.excerpt || '',
  status: props.initialData?.status || 'draft',
  tagIds: props.initialData?.tags?.map((t) => t.id) || [] as string[],
  categoryIds: props.initialData?.categories?.map((c) => c.id) || [] as string[],
});

function getErrorMessage(error: unknown): string {
  if (error instanceof Error) return error.message;
  return 'An error occurred';
}

function handleSubmit() {
  emit('submit', {
    title: form.title,
    content: form.content,
    excerpt: form.excerpt || undefined,
    status: form.status as 'draft' | 'in_review' | 'published' | 'archived',
    tagIds: form.tagIds,
    categoryIds: form.categoryIds,
  });
}
</script>
